version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: linkai_db
      POSTGRES_USER: linkai
      POSTGRES_PASSWORD: secret
    ports:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - linkai-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
    depends_on:
      - postgres
    networks:
      - linkai-network

volumes:
  pgdata:
    name: linkai_pgdata

networks:
  linkai-network:
