spring.application.name=linkai

# Conexão com o Postgres dentro do Docker
spring.datasource.url=jdbc:postgresql://postgres:5432/linkai_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=linkai
spring.datasource.password=secret

# JPA
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Token JWT ou segurança
api.security.token.secret=my-secret-key

# URL ID Generator secret key (can be provided via env var URL_ID_SECRET_KEY)
url.id.secret-key=${URL_ID_SECRET_KEY}